---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support, cloud manager, bluexp 
summary: Astra Trident は、ネットアップが管理している、完全にサポートされているオープンソースプロジェクトです。Kubernetes と Persistent Volume フレームワークとネイティブに統合されている Astra Trident は、ネットアップストレージプラットフォームを任意に組み合わせて実行されているシステムから、ボリュームのプロビジョニングと管理をシームレスに行います。 
---
= BlueXPでのKubernetesのデータ管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident は、ネットアップが管理している、完全にサポートされているオープンソースプロジェクトです。Kubernetes と Persistent Volume フレームワークとネイティブに統合されている Astra Trident は、ネットアップストレージプラットフォームを任意に組み合わせて実行されているシステムから、ボリュームのプロビジョニングと管理をシームレスに行います。 link:https://docs.netapp.com/us-en/trident/index.html["Trident の詳細をご確認ください"^]。



== の機能

を使用します link:https://docs.netapp.com/us-en/bluexp-setup-admin/index.html["BlueXP"^] Tridentオペレータを使用して互換性のあるバージョンのAstra Tridentを導入すると、次のことが可能になります。

* Kubernetesクラスタを追加および管理します
* link:./task/task-k8s-manage-trident.html["Astra Tridentをインストール、アップグレード、アンインストール"]
* link:./task/task-k8s-manage-storage-classes.html["ストレージクラスを追加および削除します"]
* link:./task/task-k8s-manage-persistent-volumes.html["永続ボリュームを表示します"]
* link:./task/task-k8s-manage-remove-cluster.html["Kubernetesクラスタを削除"] をクリックします
* link:./task/task-kubernetes-enable-services.html["BlueXPのバックアップとリカバリのアクティブ化と表示"]




== サポートされる Kubernetes 環境

BlueXPは、次の環境で実行されるマネージドKubernetesクラスタをサポートしています。

* link:./requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes Service （ Amazon EKS ）"]
* link:./requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes Service （ AKS ）"]
* link:./requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine （ GKE ）"]




== サポートされている Astra Trident 環境

Astra Tridentの4つの最新バージョンのうちの1つ link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["Tridentオペレータを使用して導入されています"^] は必須です。


NOTE: を使用してTridentを導入 `tridentctl` はサポートされていません。を使用してAstra Tridentを導入した場合 `tridentctl`では、BlueXPを使用してKubernetesクラスタを管理することはできません。実行する必要があります  再インストールしてください link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["Trident演算子を使用する"^] または link:./task/task-k8s-manage-trident.html["BlueXPを使用している"]。

Astra Tridentは、BlueXPから直接インストールすることも、サポート対象バージョンにアップグレードすることもできます。

link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["Astra Tridentの前提条件を確認"^]



== サポートされるバックエンドストレージ

NetApp Astra Tridentは各Kubernetesクラスタにインストールする必要があります。また、Cloud Volumes ONTAP またはAmazon FSX for ONTAP は、クラスタのバックエンドストレージとして設定する必要があります。



== コスト

BlueXPでは'_discover _で使用しているKubernetesクラスタには料金は発生しませんがCloud Backup Service を使用して永続ボリュームをバックアップする場合には課金されます
