---
settings:
  name: Kubernetes clusters
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,ko-kr
sidebar:
  entries:
  - title: Cloud Manager のすべてのドキュメント
    url: https://docs.netapp.com/us-en/cloud-manager-family
  - title: Kubernetes のドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: Kubernetes のデータ管理について説明します
      url: "/concept-kubernetes.html"
  - title: 要件
    entries:
    - title: AWS 上の Kubernetes クラスタ
      url: "/requirements/kubernetes-reqs-aws.html"
    - title: Azure 上の Kubernetes クラスタ
      url: "/requirements/kubernetes-reqs-aks.html"
    - title: Google Cloud の Kubernetes クラスタ
      url: "/requirements/kubernetes-reqs-gke.html"
  - title: Kubernetes クラスタを追加
    entries:
    - title: AWS にクラスタを追加します
      url: "/task/task-kubernetes-discover-aws.html"
    - title: Azure でクラスタを追加
      url: "/task/task-kubernetes-discover-azure.html"
    - title: Google Cloud にクラスタを追加します
      url: "/task/task-kubernetes-discover-gke.html"
  - title: Kubernetes クラスタでデータサービスを有効化
    url: "/task/task-kubernetes-enable-services.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/support/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/support/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: 新機能
      url: "/whats-new.html"
    - title: Kubernetes のデータ管理について説明します
      url: "/concept-kubernetes.html"
  - title: 要件
    links:
    - title: AWS 上の Kubernetes クラスタ
      url: "/requirements/kubernetes-reqs-aws.html"
    - title: Azure 上の Kubernetes クラスタ
      url: "/requirements/kubernetes-reqs-aks.html"
    - title: Google Cloud の Kubernetes クラスタ
      url: "/requirements/kubernetes-reqs-gke.html"
  - title: Kubernetes クラスタを追加
    links:
    - title: AWS にクラスタを追加します
      url: "/task/task-kubernetes-discover-aws.html"
    - title: Azure でクラスタを追加
      url: "/task/task-kubernetes-discover-azure.html"
    - title: Google Cloud にクラスタを追加します
      url: "/task/task-kubernetes-discover-gke.html"
  - title: データサービスを有効化
    links:
    - title: データサービスを有効化
      url: "/task/task-kubernetes-enable-services.html"
  - title: Cloud Manager のヘルプを参照してください
    links:
    - title: サポートに登録します
      url: "/support/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/support/task-get-help.html"
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central のブログです
      url: https://cloud.netapp.com/blog
    - title: クラウドに関する Web セミナー
      url: https://cloud.netapp.com/events
product-family: {}
